FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc g++ cron && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY forecast.py entrypoint.sh ./
RUN chmod +x entrypoint.sh

# สร้าง log file
RUN touch /var/log/forecast.log

CMD ["/app/entrypoint.sh"]
